### ISSUE TITLE
9系统 点击反编译会闪退

### ISSUE THREAD

**Issue by maofuqiang** [lulululbj/Box#4]
华为P20PRO 安装后点击反编译闪退

**Comment by lulululbj** [comment]
如果可以的话，提供一下日志

**Comment by maofuqiang** [comment]
> 如果可以的话，提供一下日志

2019-11-14 14:10:09.994 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:10.019 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:10.718 1897-3358/? E/DollieActivityManagerAdapter: HwActivityNotifierEx null uid
2019-11-14 14:10:10.726 745-952/? E/JankService: specialActionEntryHandler: should reset and not report
2019-11-14 14:10:10.726 745-952/? E/JankService: specialActionEntryHandler: should reset and not report
2019-11-14 14:10:10.746 30304-30304/? E/awei.trustspac: Not starting debugger since process cannot load the jdwp agent.
2019-11-14 14:10:10.752 1229-1873/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2019-11-14 14:10:10.769 1229-1873/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2019-11-14 14:10:10.770 735-781/? E/AwareLog: iawared: WorkingsetPathCheckInternal Failed to lstat(/data/system/iaware/workingset/): Permission denied
2019-11-14 14:10:10.770 735-781/? E/AwareLog: iawared: WorkingsetPathCheck Failed to create directory(/data/system/iaware/workingset/): Permission denied
2019-11-14 14:10:10.776 30320-30320/? E/luyao.box: Not starting debugger since process cannot load the jdwp agent.
2019-11-14 14:10:10.798 1959-3032/? E/AwareLog: GameSdkConfigReader: GameSdkLog: idNameMap: null
2019-11-14 14:10:10.801 30304-30318/? E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-11-14 14:10:10.801 1897-2383/? E/Hicom_PolicyCenterService: enableAppLevelMP. null == mMultipathAppsMap
2019-11-14 14:10:10.802 1959-2921/? E/AwareLog: SPKSchedFeature: Uid has been sent, ignore.
2019-11-14 14:10:10.802 1959-2921/? E/AwareLog: SPKEQSchedFeature: Uid has been sent, ignore.
2019-11-14 14:10:10.804 1897-2383/? E/XEngineMpipControl: Invalid SubId
2019-11-14 14:10:10.825 30320-30340/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@700d2e0
2019-11-14 14:10:10.825 30320-30340/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@4da3999
2019-11-14 14:10:10.829 30320-30334/? E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-11-14 14:10:10.833 1897-3358/? E/HsmCoreServiceImpl: onTransact in code is: 103
2019-11-14 14:10:10.835 2003-21600/? E/ndroid.launche: Failed to open APK '/data/app/com.tujia.hotel-SlW8vUiEihCiWRbAN_ZqNg==/base.apk' I/O error
2019-11-14 14:10:10.835 2003-21600/? E/ResourcesManager: failed to add asset path /data/app/com.tujia.hotel-SlW8vUiEihCiWRbAN_ZqNg==/base.apk
2019-11-14 14:10:10.835 2003-21600/? E/ndroid.launche: Failed to open APK '/data/app/com.tujia.hotel-SlW8vUiEihCiWRbAN_ZqNg==/base.apk' I/O error
2019-11-14 14:10:10.835 2003-21600/? E/ResourcesManager: failed to add asset path /data/app/com.tujia.hotel-SlW8vUiEihCiWRbAN_ZqNg==/base.apk
2019-11-14 14:10:10.918 1229-1721/? E/HiDATA_HiNetwork: monitor handleActivityChange curPkgName is luyao.box curUid is 10778 lastPkgName is :com.huawei.android.launcher
2019-11-14 14:10:10.923 1897-9737/? E/DollieAdapterService: notifyActivityState pkg:luyao.box/luyao.box.ui.MainActivity state:2 fg:true mUid:10778
2019-11-14 14:10:10.924 1229-1721/? E/HiDATA_HiNetwork: onAppStart packageName is luyao.box
2019-11-14 14:10:10.924 1229-1721/? E/HiDATA_HiNetwork: contain db file packageName: luyao.box iscanacce:-1
2019-11-14 14:10:10.924 1229-1721/? E/HiDATA_HiNetwork: onAppStart stop timer.
2019-11-14 14:10:10.925 1229-1721/? E/HiDATA_HiNetwork: key is :1573711810925
2019-11-14 14:10:10.926 3511-3676/? E/[HwRecSys]HwRecSysService: getIsRportDirectService is false!
2019-11-14 14:10:10.926 1229-30351/? E/HiDATA_HiNetwork: bindAidl Thread run 
2019-11-14 14:10:10.928 1897-1897/? E/SmartDualCardTraffic: getMealTrafficImpl fail,invalid imsi
2019-11-14 14:10:10.929 1229-30351/? E/HiDATA_HiNetwork: bindAidl true
2019-11-14 14:10:10.940 1229-1873/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2019-11-14 14:10:10.945 30352-30352/? E/i.gameassistan: Not starting debugger since process cannot load the jdwp agent.
2019-11-14 14:10:10.950 626-910/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:10.957 626-910/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:10.961 626-910/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:10.975 626-1737/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:11.018 30352-30384/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@43df374
2019-11-14 14:10:11.018 30352-30384/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@e46309d
2019-11-14 14:10:11.034 1229-8103/? E/WifiService: enforceCanAccessScanResults: hiding ssid and bssidLocation mode is disabled for the device
2019-11-14 14:10:11.061 1897-9737/? E/DollieAdapterService: notifyActivityState pkg:com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher state:4 fg:false mUid:10070
2019-11-14 14:10:11.069 30352-30386/? E/HwGameAssistant-9.2.0.302-SecurityUtil: isInit is true
2019-11-14 14:10:11.070 30352-30378/? E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-11-14 14:10:11.090 1229-2157/? E/WindowManager: win=Window{14e858 u0 com.huawei.intelligent.Workspace} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false
2019-11-14 14:10:11.091 1229-2157/? E/WindowManager: win=Window{e199d33 u0 com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false
2019-11-14 14:10:11.091 30352-30388/? E/HwGameAssistant-9.2.0.302-BoosterModelValidHelper: access JXS Server failed: httpStatusCode = 404, exception = null
2019-11-14 14:10:11.093 1229-1229/? E/HiDATA_HiNetwork: onServiceConnected aidl
2019-11-14 14:10:11.094 1959-3032/? E/AwareLog: GameSdkConfigReader: GameSdkLog: idNameMap: null
2019-11-14 14:10:11.137 1229-1586/? E/WindowManager: win=Window{5cd4cd7 u0 Splash Screen luyao.box EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
2019-11-14 14:10:12.342 1229-1794/? E/WifiService: enforceCanAccessScanResults: hiding ssid and bssidLocation mode is disabled for the device
2019-11-14 14:10:13.029 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:13.067 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:13.930 1229-1721/? E/HiDATA_HiNetwork: getEstablishedInfo packageName is :luyao.box
2019-11-14 14:10:13.941 1229-1721/? E/HiDATA_HiNetwork: getEstablishedInfo error, result is null
2019-11-14 14:10:13.941 1229-1721/? E/HiDATA_HiNetwork: startTimer, messageType is :9
2019-11-14 14:10:13.945 30352-30395/? E/HwGameAssistant-9.2.0.302-BoosterModelValidHelper: access JXS Server failed: httpStatusCode = 404, exception = null
2019-11-14 14:10:14.420 730-730/? E/Thermal-daemon: [ap] temp_new :31  temp_old :30
2019-11-14 14:10:14.422 730-730/? E/Thermal-daemon: Report temperature: [ap] temp :31  report_threshold:1
2019-11-14 14:10:14.889 1229-1644/? E/WificondControl: Noise: -86, Snr: 35, Chload: -1
2019-11-14 14:10:16.075 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:16.103 1229-1644/? E/WificondControl: Noise: -86, Snr: 35, Chload: -1
2019-11-14 14:10:18.526 1229-1721/? E/HiDATA_HiNetwork: monitor handleActivityChange curPkgName is luyao.box curUid is 10778 lastPkgName is :luyao.box
2019-11-14 14:10:18.526 1897-9737/? E/DollieAdapterService: notifyActivityState pkg:luyao.box/luyao.box.ui.appManager.AppManagerActivity state:2 fg:true mUid:10778
2019-11-14 14:10:18.534 3511-3676/? E/[HwRecSys]HwRecSysService: getIsRportDirectService is false!
2019-11-14 14:10:18.584 1897-1911/? E/HsmCoreServiceImpl: onTransact in code is: 103
2019-11-14 14:10:18.880 1229-1324/? E/WindowManager: win=Window{c137f06 u0 luyao.box/luyao.box.ui.MainActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false
2019-11-14 14:10:19.110 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:19.124 1229-1644/? E/WificondControl: Noise: -88, Snr: 35, Chload: -1
2019-11-14 14:10:20.455 30320-30345/? E/luyao.box: No package ID 7f found for ID 0x7f02038c.
2019-11-14 14:10:20.455 30320-30345/? E/luyao.box: Failed to open APK '/storage/emulated/0/Download/browser/3.4.2_a1000.apk' Invalid file
    
    --------- beginning of crash
2019-11-14 14:10:20.456 30320-30345/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: luyao.box, PID: 30320
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
        at luyao.box.util.AppManager.a(Unknown Source:88)
        at luyao.box.ui.appManager.AppViewModel$getLocalApkList$1.invokeSuspend(Unknown Source:40)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:9)
        at kotlinx.coroutines.o0.run(Unknown Source:80)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.a(Unknown Source:0)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.a(Unknown Source:0)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$b.run(Unknown Source:54)
2019-11-14 14:10:20.467 745-3054/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.468 745-3054/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.470 745-3054/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.470 745-31742/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.475 745-31742/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.476 745-31742/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.479 745-31742/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.480 745-31745/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.481 745-31745/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.484 745-31745/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.484 745-31745/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.484 745-31745/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.485 745-31746/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.486 745-31746/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.486 745-31746/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.487 745-31746/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
2019-11-14 14:10:20.493 745-1390/? E/libc: Access denied finding property "ro.patchversion"
2019-11-14 14:10:20.553 745-952/? E/JankService: logCaptureFilter: the special scene
2019-11-14 14:10:20.616 1897-1911/? E/HsmCoreServiceImpl: onTransact in code is: 103
2019-11-14 14:10:20.633 1229-1624/? E/InputDispatcher: channel '95f704a luyao.box/luyao.box.ui.appManager.AppManagerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-11-14 14:10:20.633 1229-1624/? E/InputDispatcher: channel 'c137f06 luyao.box/luyao.box.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-11-14 14:10:20.652 1229-1329/? E/HwAudioService: IAware onForegroundActivitiesChanged return data is null
2019-11-14 14:10:20.653 1959-3032/? E/AwareLog: GameSdkConfigReader: GameSdkLog: idNameMap: null
2019-11-14 14:10:20.654 1897-2383/? E/Hicom_PolicyCenterService: handleAppDied. null == mMultipathAppsMap
2019-11-14 14:10:20.654 1897-10120/? E/HsmCoreServiceImpl: onTransact in code is: 102
2019-11-14 14:10:20.671 1229-2452/? E/WindowManager: win=Window{95f704a u0 luyao.box/luyao.box.ui.appManager.AppManagerActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
2019-11-14 14:10:20.695 1897-1911/? E/DollieActivityManagerAdapter: HwActivityNotifierEx null uid
2019-11-14 14:10:20.711 1897-9737/? E/DollieAdapterService: notifyActivityState pkg:luyao.box/luyao.box.ui.appManager.AppManagerActivity state:18 fg:false mUid:10778
2019-11-14 14:10:20.737 1229-1873/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2019-11-14 14:10:20.738 735-781/? E/AwareLog: iawared: WorkingsetPathCheckInternal Failed to lstat(/data/system/iaware/workingset/): Permission denied
2019-11-14 14:10:20.738 735-781/? E/AwareLog: iawared: WorkingsetPathCheck Failed to create directory(/data/system/iaware/workingset/): Permission denied
2019-11-14 14:10:20.745 30422-30422/? E/luyao.box: Not starting debugger since process cannot load the jdwp agent.
2019-11-14 14:10:20.783 1959-3032/? E/AwareLog: GameSdkConfigReader: GameSdkLog: idNameMap: null
2019-11-14 14:10:20.794 1959-2921/? E/AwareLog: SPKSchedFeature: Uid has been sent, ignore.
2019-11-14 14:10:20.794 1959-2921/? E/AwareLog: SPKEQSchedFeature: Uid has been sent, ignore.
2019-11-14 14:10:20.798 1897-2383/? E/Hicom_PolicyCenterService: enableAppLevelMP. null == mMultipathAppsMap
2019-11-14 14:10:20.811 30422-30441/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@aff21a4
2019-11-14 14:10:20.811 30422-30441/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@3b97b0d
2019-11-14 14:10:20.813 30422-30436/? E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-11-14 14:10:20.939 1229-1721/? E/HiDATA_HiNetwork: monitor handleActivityChange curPkgName is luyao.box curUid is 10778 lastPkgName is :luyao.box
2019-11-14 14:10:20.946 1897-9737/? E/DollieAdapterService: notifyActivityState pkg:luyao.box/luyao.box.ui.MainActivity state:2 fg:true mUid:10778
2019-11-14 14:10:20.953 3511-3676/? E/[HwRecSys]HwRecSysService: getIsRportDirectService is false!
2019-11-14 14:10:20.953 1897-1897/? E/SmartDualCardTraffic: getMealTrafficImpl fail,invalid imsi
2019-11-14 14:10:20.960 1897-1897/? E/SmartDualCardTraffic: getMealTrafficImpl fail,invalid imsi
2019-11-14 14:10:20.969 626-1389/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:20.973 1897-1897/? E/SmartDualCardTraffic: getMealTrafficImpl fail,invalid imsi
2019-11-14 14:10:20.978 626-1389/? E/BufferQueueProducer: [] mConsumerName == NULL!!!!!!
2019-11-14 14:10:21.160 1229-1586/? E/WindowManager: win=Window{8847150 u0 Splash Screen luyao.box EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
2019-11-14 14:10:22.136 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:22.166 1229-1644/? E/WificondControl: Noise: -88, Snr: 35, Chload: -1
2019-11-14 14:10:22.899 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:24.902 1897-1897/? E/SmartDualCardSM: queryCellSignalLevel fail,netType UNKNOWN
2019-11-14 14:10:25.178 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:25.204 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:25.245 30476-30476/? E/JankService: child Thread receive to stop
2019-11-14 14:10:25.385 745-950/? E/JankService: all data read ok
2019-11-14 14:10:28.212 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:28.239 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:28.454 1229-1229/? E/PowerManagerService: Exception when search wack lock :java.lang.IllegalArgumentException: Wake lock not active: android.os.Binder@5652ee0 from uid 1000
2019-11-14 14:10:29.430 730-730/? E/Thermal-daemon: [shell_frame] temp_new :28  temp_old :27
2019-11-14 14:10:29.432 730-730/? E/Thermal-daemon: Report temperature: [shell_frame] temp :28  report_threshold:1
2019-11-14 14:10:30.577 2271-21837/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:718006122>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/contextcontroller
    rli: Long live credential not available.
        at jew.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):61)
        at jdw.a(Unknown Source:2)
        at jdu.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):15)
        at jdu.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at hek.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):32)
        at hek.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):79)
        at heu.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):3)
        at her.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at her.c(:com.google.android.gms@17785037@17.7.85 (100400-253824076):6)
        at her.b(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at hep.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at sdu.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at sch.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at eul.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):24)
        at epg.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at epe.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at epe.handleMessage(Unknown Source:0)
        at skd.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):8)
        at skq.b(:com.google.android.gms@17785037@17.7.85 (100400-253824076):37)
        at skq.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):21)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sqo.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:784)
2019-11-14 14:10:30.629 2271-21837/? E/ctxmgr: [BaseServerTask] Server task (WriteInterestRecordTask) got error statusCode=-1. [CONTEXT service_id=47 ]
    com.android.volley.VolleyError: Unable to obtain auth token - is the device online?
        at eul.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):31)
        at epg.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at epe.a(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at epe.handleMessage(Unknown Source:0)
        at skd.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):8)
        at skq.b(:com.google.android.gms@17785037@17.7.85 (100400-253824076):37)
        at skq.run(:com.google.android.gms@17785037@17.7.85 (100400-253824076):21)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sqo.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:784)
2019-11-14 14:10:30.632 2271-21837/? E/ctxmgr: [SyncServerInterestRecordsOperation]Failed WriteInterestRecord: network status=-1 [CONTEXT service_id=47 ]
2019-11-14 14:10:30.903 1229-1644/? E/WificondControl: Noise: -86, Snr: 35, Chload: -1
2019-11-14 14:10:30.909 1897-1897/? E/SmartDualCardSM: queryCellSignalLevel fail,netType UNKNOWN
2019-11-14 14:10:31.249 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:31.281 1229-1644/? E/WificondControl: Noise: -86, Snr: 35, Chload: -1
2019-11-14 14:10:34.294 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:34.325 1229-1644/? E/WificondControl: Noise: -84, Snr: 35, Chload: -1
2019-11-14 14:10:34.436 730-730/? E/Thermal-daemon: [battery] temp_new :29  temp_old :28
2019-11-14 14:10:34.438 730-730/? E/Thermal-daemon: Report temperature: [battery] temp :29  report_threshold:1
2019-11-14 14:10:36.919 1897-1897/? E/SmartDualCardSM: queryCellSignalLevel fail,netType UNKNOWN
2019-11-14 14:10:37.159 1927-2064/? E/HwCHRWifiRSSIGroupSummery: updatArpSummery mRSSI:-1  HwCHRWifiRSSIGroup [rssi_index=4, rtt_tcp_packets=0, rtt_tcp_duration=0, rtt_lan_duration=83171, rtt_lan_failures=50, rtt_lan_succ=4841, rtt_lan_max=577, rtt_lan_min=1,same_area_frequency=6,adjacent_area_frequency=6]
2019-11-14 14:10:37.338 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:37.356 1229-1644/? E/WificondControl: Noise: -84, Snr: 34, Chload: -1
2019-11-14 14:10:38.911 1229-1644/? E/WificondControl: Noise: -85, Snr: 34, Chload: -1
2019-11-14 14:10:40.365 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:40.392 1229-1644/? E/WificondControl: Noise: -86, Snr: 35, Chload: -1
2019-11-14 14:10:42.923 1897-1897/? E/SmartDualCardSM: queryCellSignalLevel fail,netType UNKNOWN
2019-11-14 14:10:43.406 622-622/? E/WifiHAL: enter wifi_get_link_stats
2019-11-14 14:10:43.434 1229-1644/? E/WificondControl: Noise: -87, Snr: 35, Chload: -1
2019-11-14 14:10:43.948 1229-30396/? E/HiDATA_HiNetwork: send message, messageType is :9
2019-11-14 14:10:43.949 1229-1721/? E/HiDATA_HiNetwork: unbindService with gameassistant.
2019-11-14 14:10:44.450 730-730/? E/Thermal-daemon: [ap] temp_new :30  temp_old :31
2019-11-14 14:10:44.451 730-730/? E/Thermal-daemon: Report temperature: [ap] temp :30  report_threshold:1
![image](https://user-images.githubusercontent.com/12031603/68831190-a940d880-06e8-11ea-8630-2fc4b89ac89a.png)
